from pathlib import Path
import re
import pandas as pd
import shutil


INPUT_DIR = "filtered_heights/"
OUTPUT_DIR = "height_stats/"


def combine_winners_losers(df):
    """
    This converts a dataframe with columns:
    winner_id, winner_name, winner_ht, loser_id, loser_name, loser_ht
    to a dataframe with columns:
    id, name, ht
    By renaming the columns and pasting the loser data below the winner data
    """
    winners = df[["winner_id", "winner_name", "winner_ht"]].rename(
        columns={
            "winner_id": "id",
            "winner_name": "name",
            "winner_ht": "ht",
        }
    )

    losers = df[["loser_id", "loser_name", "loser_ht"]].rename(
        columns={
            "loser_id": "id",
            "loser_name": "name",
            "loser_ht": "ht",
        }
    )

    # Simply pastes the rows together. The ignore_index makes it so that the
    # index of the loser portion of data does not start at 0, it starts at
    # len(winners).
    return pd.concat([winners, losers], ignore_index=True)


def get_row(df, match):
    year = int(match.group("year"))
    match_type = match.group("match_type")
    mean_ht = df["ht"].mean()
    # Sample std by default, so ddof=1
    std_ht = df["ht"].std()
    return {"year": year, "match_type": match_type, "mean": mean_ht, "std": std_ht}


# To clear the output folder.
def clear_output():
    p = Path(OUTPUT_DIR)
    if p.exists():
        shutil.rmtree(p)
    return p


def write_output(df):
    clear_output()
    path = f"{OUTPUT_DIR}/"
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    out_fn = f"{path}/height_stats.csv"
    wide = df.pivot(
        index="year", columns="match_type", values=["mean", "std"]
    ).sort_index()

    # Flatten columns so CSV has simple headers
    wide.columns = [f"{stat}_{mt}" for stat, mt in wide.columns]

    wide.to_csv(out_fn, index=True)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1

    # Should not be needed for filtering, but serves as a small sanity check.
    # It is also conventient to extract the fields from the name.
    p_pattern = re.compile(
        r"filtered_heights/(?P<year>\d{4})/ht_(?P<match_type>[\w_]+).csv"
    )
    # To store the output rows.
    rows = []
    # Will list every .csv in filtered_heights.
    for p in data_path.rglob("*.csv"):
        match = re.search(p_pattern, str(p))
        # Should always be true unless filtered_heights was manually altered,
        # but this is cleaner.
        if match:
            df = pd.read_csv(p)
            df = combine_winners_losers(df)
            rows.append(get_row(df, match))

    out = pd.DataFrame(rows)
    write_output(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
