from pathlib import Path
import re
import pandas as pd
import shutil


INPUT_DIR = "filtered_heights_diff"
OUTPUT_DIR = "filtered_heights_diff_stats"


# To clear the output folder.
def clear_output():
    p = Path(OUTPUT_DIR)
    if p.exists():
        shutil.rmtree(p)
    return p


def get_row(df, match):
    year = int(match.group("year"))
    match_type = match.group("match_type")
    # Get the mean of the height deltas.
    mean_dh = df["dh"].mean()
    return {"year": year, "match_type": match_type, "dh_mean": mean_dh}


# TODO
def write_output(df):
    clear_output()
    path = f"{OUTPUT_DIR}/"
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    out_fn = f"{path}/height_diff_stats.csv"
    wide = df.pivot(index="year", columns="match_type", values=["dh_mean"]).sort_index()

    wide.columns = [f"{stat}_{mt}" for stat, mt in wide.columns]
    wide.to_csv(out_fn, index=True)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run height_matchup_diff.py first, this script depends on the data generated by it."
        )
        return 1

    # Should not be needed for filtering, but serves as a small sanity check.
    # It is also conventient to extract the fields from the name.
    p_pattern = re.compile(
        r"filtered_heights_diff/(?P<year>\d{4})/ht_diff_(?P<match_type>[\w_]+).csv"
    )

    # Refresh the output dir.
    clear_output()

    # To store the output rows.
    rows = []

    # Will list every .csv in filtered_heights.
    for p in data_path.rglob("*.csv"):
        match = re.search(p_pattern, str(p))
        if match:
            print(p)
            df = pd.read_csv(p)
            rows.append(get_row(df, match))

    out = pd.DataFrame(rows)
    write_output(out)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
