from pathlib import Path
import re
import pandas as pd
import shutil


INPUT_DIR = "filtered_heights"
OUTPUT_DIR = "filtered_heights_diff"


# To clear the output folder.
def clear_output():
    p = Path(OUTPUT_DIR)
    if p.exists():
        shutil.rmtree(p)
    return p


def write_output(df, year, match_type):
    path = f"{OUTPUT_DIR}/{year}"
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    out_fn = f"{path}/ht_diff_{match_type}.csv"
    df.to_csv(out_fn, index=False)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1

    # Should not be needed for filtering, but serves as a small sanity check.
    # It is also conventient to extract the fields from the name.
    p_pattern = re.compile(
        r"filtered_heights/(?P<year>\d{4})/ht_(?P<match_type>[\w_]+).csv"
    )

    # Refresh the output dir.
    clear_output()

    dataframes = []
    # Will list every .csv in filtered_heights.
    for p in data_path.rglob("*.csv"):
        match = re.search(p_pattern, str(p))
        # Should always be true unless filtered_heights was manually altered,
        # but this is cleaner.
        if match:
            df = pd.read_csv(p)
            dataframes.append(df.copy(deep=True))
            df["dh"] = df["winner_ht"] - df["loser_ht"]
            out = df[["dh"]]

            year = match.group("year")
            match_type = match.group("match_type")
            write_output(out, year, match_type)

    df = pd.concat(dataframes, ignore_index=True)
    df["dh"] = df["winner_ht"] - df["loser_ht"]
    out = df[["dh"]]
    out.to_csv(f"{OUTPUT_DIR}/all_dh.csv")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
