import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from pathlib import Path
import statsmodels.formula.api as smf
import shutil


INPUT_DIR = "filtered_heights"
OUTPUT_DIR = "logit_csv"

FP_PATTERN = re.compile(rf"{INPUT_DIR}/(?P<year>\d{{4}})/ht_(?P<match_type>[\w_]+).csv")


# To clear the output folder.
def clear_output():
    p = Path(OUTPUT_DIR)
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)
    return p


def write_output(df, year, match_type):
    path = f"{OUTPUT_DIR}/{year}"
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    out_fn = f"{path}/logit_{match_type}.csv"
    df.to_csv(out_fn, index=False)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1
    clear_output()
    # We only care about match outcomes now
    cols = [
        "winner_ht",
        "loser_ht",
    ]

    for fn in data_path.rglob("*.csv"):
        fn_match = re.search(FP_PATTERN, str(fn))
        if fn_match:
            print(f"Processing: {fn}…")
            year = int(fn_match.group("year"))
            match_type = fn_match.group("match_type")
            df = pd.read_csv(fn, usecols=cols)  # pyright: ignore

            # Logistic regression needs both a winner and a loser perspective to train the model.
            rows = []
            for _, r in df.iterrows():
                winner_row = {
                    "player_ht": r["winner_ht"],
                    "opponent_ht": r["loser_ht"],
                    "win": 1,
                }
                loser_row = {
                    "player_ht": r["loser_ht"],
                    "opponent_ht": r["winner_ht"],
                    "win": 0,
                }
                rows.append(winner_row)
                rows.append(loser_row)
            df = pd.DataFrame(rows)
            # Write
            write_output(df, year, match_type)
        else:
            print(f"Invalid: {fn}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
