from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt


INPUT_DIR = "height_stats"
OUTPUT_DIR = "height_stats"


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run height_stats.py first, this script depends on the data generated by it."
        )
        return 1

    # Should be sorted already but to be safe.
    df = pd.read_csv(f"{INPUT_DIR}/height_stats.csv").sort_values("year")

    types = ["singles", "qual_chall", "futures"]

    plt.figure(figsize=(10, 8))

    for t in types:
        mean_col = f"mean_{t}"
        std_col = f"std_{t}"

        sub = df[["year", mean_col, std_col]].dropna()

        # Commented the errorbar code as it turned the graph into a mess. A
        # todo perhaps.
        plt.errorbar(
            sub["year"],
            sub[mean_col],
            # yerr=sub[std_col],
            fmt="o-",
            capsize=2,
            alpha=0.6,
            # errorevery=5,
            label=t,
        )

    plt.xlabel("Year")
    plt.ylabel("Height mean (cm)")
    plt.title("Mean height by year")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{OUTPUT_DIR}/height_stats_plot.png")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
