import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from pathlib import Path
import statsmodels.formula.api as smf

INPUT_DIR = "filtered_ages"

FP_PATTERN = re.compile(
    rf"{INPUT_DIR}/(?P<year>\d{{4}})/age_(?P<match_type>[\w_]+).csv"
)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1
    # We only care about match outcomes now
    cols = [
        "winner_age",
        "loser_age",
    ]

    dataframes = []

    for fn in data_path.rglob("*.csv"):
        fn_match = re.search(FP_PATTERN, str(fn))
        if fn_match:
            print(f"Processing: {fn}…")
            year = int(fn_match.group("year"))
            match_type = fn_match.group("match_type")
            df = pd.read_csv(fn, usecols=cols)  # pyright: ignore

            # Logistic regression needs both a winner and a loser perspective to train the model.
            rows = []
            for _, r in df.iterrows():
                rows.append(
                    {
                        "player_age": r["winner_age"],
                        "opponent_age": r["loser_age"],
                        "win": 1,
                    }
                )
                rows.append(
                    {
                        "player_age": r["loser_age"],
                        "opponent_age": r["winner_age"],
                        "win": 0,
                    }
                )
            df = pd.DataFrame(rows)

            dataframes.append(df)
    df = pd.concat(dataframes, ignore_index=True)
    # print(len(df))
    df = df.dropna(subset=["player_age", "opponent_age", "win"])
    # print(len(df))

    # Behoorlijke todo om dit te begrijpen.
    model = smf.logit(
        "win ~ bs(player_age, df=6) + bs(opponent_age, df=6)", data=df
    ).fit()
    print(model.summary())
    # TODO
    age_min, age_max = 16, 40
    grid = np.linspace(age_min, age_max, 150)

    P, O = np.meshgrid(grid, grid)
    pred_df = pd.DataFrame({"player_age": P.ravel(), "opponent_age": O.ravel()})

    Z = model.predict(pred_df).values.reshape(P.shape)

    plt.figure(figsize=(6.5, 5.5))
    plt.imshow(
        Z, origin="lower", extent=[age_min, age_max, age_min, age_max], aspect="auto"
    )
    plt.xlabel("Player age")
    plt.ylabel("Opponent age")
    plt.title("Predicted win probability (2024 singles)\nSpline on absolute ages")
    plt.colorbar(label="Win probability")
    plt.tight_layout()
    plt.savefig("tmp.png")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
