import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from pathlib import Path
import statsmodels.formula.api as smf
import shutil


INPUT_DIR = "filtered_ages"
OUTPUT_DIR = "logit_csv"

FP_PATTERN = re.compile(
    rf"{INPUT_DIR}/(?P<year>\d{{4}})/age_(?P<match_type>[\w_]+).csv"
)


# To clear the output folder.
def clear_output():
    p = Path(OUTPUT_DIR)
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)
    return p


def write_output(df, year, match_type):
    path = f"{OUTPUT_DIR}/{year}"
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    out_fn = f"{path}/logit_{match_type}.csv"
    df.to_csv(out_fn, index=False)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1
    clear_output()
    # We only care about match outcomes now
    cols = [
        "winner_age",
        "loser_age",
    ]

    for fn in data_path.rglob("*.csv"):
        fn_match = re.search(FP_PATTERN, str(fn))
        if fn_match:
            print(f"Processing: {fn}…")
            year = int(fn_match.group("year"))
            match_type = fn_match.group("match_type")
            df = pd.read_csv(fn, usecols=cols)  # pyright: ignore

            # Logistic regression needs both a winner and a loser perspective to train the model.
            rows = []
            for _, r in df.iterrows():
                rows.append(
                    {
                        "player_age": r["winner_age"],
                        "opponent_age": r["loser_age"],
                        "win": 1,
                    }
                )
                rows.append(
                    {
                        "player_age": r["loser_age"],
                        "opponent_age": r["winner_age"],
                        "win": 0,
                    }
                )
            df = pd.DataFrame(rows)
            df.dropna(subset=["player_age", "opponent_age", "win"])
            write_output(df, year, match_type)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
