import pandas as pd
import re
from pathlib import Path
import shutil

INPUT_DIR = "filtered_ages"

FP_PATTERN = re.compile(
    rf"{INPUT_DIR}/(?P<year>\d{{4}})/age_(?P<match_type>[\w_]+).csv"
)


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1
    # We only care about match outcomes now
    cols = [
        "winner_age",
        "loser_age",
    ]

    data = dict()
    dataframes = []
    match_types = set()

    for fn in data_path.rglob("*.csv"):
        fn_match = re.search(FP_PATTERN, str(fn))
        if fn_match:
            print(f"Processing: {fn}…")
            year = int(fn_match.group("year"))
            if year not in data:
                data[year] = dict()
            match_type = fn_match.group("match_type")
            match_types.add(match_type)
            df = pd.read_csv(fn, usecols=cols)  # pyright: ignore
            data[year][match_type] = df
            dataframes.append(df)
    match_types = list(match_types)
    df = pd.concat(dataframes, ignore_index=True)
    df["da"] = df["winner_age"] - df["loser_age"]
    print(
        f"The average age difference of the winner across all the data is {df["da"].mean()}"
    )

    # Delta age
    da = dict()

    rows = []
    for year in sorted(data):
        if year not in da:
            da[year] = dict()

        # For the year total.
        cur_data = []
        for mt in match_types:
            # Get the data of this year for this type. Might be None.
            df = data[year].get(mt)
            if df is not None:
                cur_data.append(df)
                df["da"] = df["winner_age"] - df["loser_age"]
                # print(f"{year} - {mt}: {df["da"].mean()}")
                rows.append({"year": year, "type": mt, "da": df["da"].mean()})
        df = pd.concat(cur_data, ignore_index=True)
        # print(f"{year} - total: {df["da"].mean()}")
        rows.append({"year": year, "type": "total", "da": df["da"].mean()})

    out = pd.DataFrame(rows, columns=["year", "type", "da"])  # pyright: ignore
    wide = out.pivot(index="year", columns="type", values="da").sort_index()
    wide.to_csv("age_diff_means.csv", index=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
