import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from pathlib import Path
import statsmodels.formula.api as smf
import shutil


INPUT_DIR = "logit_csv"
OUTPUT_DIR = "age_heatmaps"

FP_PATTERN = re.compile(
    rf"{INPUT_DIR}/(?P<year>\d{{4}})/logit_(?P<match_type>[\w_]+).csv"
)


def refresh_output():
    p = Path(OUTPUT_DIR)
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)
    return p


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1

    refresh_output()

    data = dict()
    from_year = 2020

    for fn in data_path.rglob("*.csv"):
        fn_match = re.search(FP_PATTERN, str(fn))
        if fn_match:
            year = int(fn_match.group("year"))
            if year < from_year:
                continue
            print(f"Processing: {fn}…")
            match_type = fn_match.group("match_type")
            if match_type not in data:
                data[match_type] = []

            df = pd.read_csv(fn)  # pyright: ignore

            data[match_type].append(df)
    for k in data.keys():
        # Merges the years for that match_type.
        df = pd.concat([frame for frame in data[k]], ignore_index=True)

        # print(len(df))
        df = df.dropna(subset=["player_age", "opponent_age", "win"])
        # print(len(df))

        # Behoorlijke todo om dit te begrijpen.
        model = smf.logit(
            "win ~ bs(player_age, df=5) + bs(opponent_age, df=5)", data=df
        ).fit()
        # print(model.summary())
        # TODO
        age_min, age_max = 16, 40
        grid = np.linspace(age_min, age_max, 150)

        P, O = np.meshgrid(grid, grid)
        pred_df = pd.DataFrame({"player_age": P.ravel(), "opponent_age": O.ravel()})

        Z = model.predict(pred_df).values.reshape(P.shape)

        plt.figure(figsize=(6.5, 5.5))
        plt.imshow(
            Z,
            origin="lower",
            extent=[age_min, age_max, age_min, age_max],
            aspect="auto",
        )
        plt.xlabel("Player age")
        plt.ylabel("Opponent age")
        plt.title(f"Predicted win probability (20-24 {k})\nSpline on absolute ages")
        plt.colorbar(label="Win probability")
        plt.tight_layout()
        plt.savefig(f"{OUTPUT_DIR }/{k}.png")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
