"""
Author: Stijn Jongbloed - 12902667

This file contains the code to train and test different logistic regression
models based on the age data of our dataset.
"""

import pandas as pd
import re
import statsmodels.formula.api as smf
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss, brier_score_loss
from pathlib import Path


# Originally the in- and output was stored within a directory next to the code,
# but it was decided to seperate data and code.
CSV_DIR = "../../data/tennis_atp_data/altered_data/age_analysis"


def init_out_dir():
    Path(CSV_DIR).mkdir(parents=True, exist_ok=True)


def get_formulas(age_min, age_max):
    """
    This function serves to separate the formulas from the rest of the code.
    A lot of them were generated by ChatGPT so I could see what did well and
    what did not.
    """
    formulas = []
    # C is category. I More or less just creates a new column based on the
    # formula inside ().

    # Differences.
    formulas.append(
        """
    win ~
        da
    """
    )
    formulas.append(
        """
    win ~
        I(da * year)
    """
    )
    formulas.append(
        """
    win ~
        da + year
    """
    )
    # Base splines
    for i in range(4, 10):
        formulas.append(
            f"""
        win ~
            bs(p1_age, df={i}, lower_bound={age_min}, upper_bound={age_max}) +
            bs(p2_age, df={i}, lower_bound={age_min}, upper_bound={age_max})
        """
        )
        formulas.append(
            f"""
        win ~
            cr(p1_age, df={i}) +
            cr(p2_age, df={i})
        """
        )
        formulas.append(f"win ~ bs(da, df={i})")
        formulas.append(f"win ~ cr(da, df={i})")

    formulas.append("win ~ da + I(da**2)")

    return formulas


def test(train_df, test_df, formulas):
    rows = []
    for formula in formulas:
        print(f"\tFormula: {formula}")
        model = smf.logit(formula, data=train_df).fit()

        # How probable is our test data according to the model?
        p = model.predict(test_df)
        # print(model.summary())

        y = test_df["win"].astype(int).values
        y_hat = (p >= 0.5).astype(int)

        row = {
            "formula": formula,
            "accuracy_score": accuracy_score(y, y_hat),
            "log_loss": log_loss(y, p),
            "brier_score_loss": brier_score_loss(y, p),
            "roc_auc_score": roc_auc_score(y, p),
        }
        print(f"\t\taccuracy: {round(row["accuracy_score"] * 100, 2)}")
        print(f"\t\tlogloss: {row["log_loss"]}")
        print(f"\t\tbrier: {row["brier_score_loss"]}")
        print(f"\t\tauc: {row["roc_auc_score"]}")

        rows.append(row)
    return rows


def main():
    print("Starting the training of the models using the various formulas…")
    path = Path(f"{CSV_DIR}/logit.csv")
    if not path.is_file():
        print(
            "\tlogit.csv Is missing, please run logit_csv.py before running this script."
        )
        return 1
    init_out_dir()
    df = pd.read_csv(path)

    len_raw = len(df)
    print(f"\tLength raw input: {len_raw}")
    # Won't touch categories.
    df.dropna(inplace=True)
    len_non_na = len(df)
    # Should be none
    print(
        f"\tdropna dropped {len_raw - len_non_na} rows, which is "
        f"{((len_raw - len_non_na) / len_raw * 100):.1f}%."
    )

    age_min = float(df[["p1_age", "p2_age"]].min().min())
    age_max = float(df[["p1_age", "p2_age"]].max().max())

    # This can be done inside the formulas, but far more convenient to just make
    # columns derived from the data.
    df["da"] = df["p1_age"] - df["p2_age"]
    df["abs_da"] = df["da"].abs()
    df["da_pos"] = (df["da"] > 0).astype(int)
    df["mean_age"] = (df["p1_age"] + df["p2_age"]) / 2

    # So we can split test and train based on date.
    df["year"] = pd.to_numeric(df["year"], errors="coerce")
    df.dropna(subset=["year"], inplace=True)
    df["year"] = df["year"].astype(int)

    train_years = set(range(1991, 2022))
    test_years = {2022, 2023, 2024}

    is_test_year = df["year"].isin(test_years)
    is_train_year = df["year"].isin(train_years)

    train_df = df.loc[is_train_year].copy()
    test_df = df.loc[is_test_year].copy()
    formulas = get_formulas(age_min, age_max)

    rows = test(train_df, test_df, formulas)
    # Otherwise the formula will display like it was defined in get_formulas(),
    # i.e. multiple lines.
    for row in rows:
        row["formula"] = re.sub(r"\s+", " ", row["formula"]).strip()
    results_df = pd.DataFrame(rows)

    results_df = results_df[
        ["formula", "accuracy_score", "log_loss", "brier_score_loss", "roc_auc_score"]
    ]

    print(f"\tWriting the result to {CSV_DIR}/model_results.csv")
    results_df.to_csv(f"{CSV_DIR}/model_results.csv", index=False)
    print("Done with the training of the models using the various formulas…\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
