from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

INPUT_DIR = "filtered_heights_diff_stats"
OUTPUT_DIR = "filtered_heights_diff_stats"


def main():
    # / serves as a concat operator with Path.
    data_path = Path(INPUT_DIR) / "height_diff_stats.csv"

    if not data_path.exists():
        print(
            "You need to run height_matchup_diff_compute.py first, this script depends on the data generated by it."
        )
        return 1

    df = pd.read_csv(data_path)

    for col in ["dh_mean_futures", "dh_mean_qual_chall", "dh_mean_singles"]:
        sub = df[["year", col]].dropna()
        x = sub["year"].to_numpy(dtype=float)
        y = sub[col].to_numpy(dtype=float)

        plt.figure(figsize=(8, 6))
        plt.scatter(x, y)

        slope, intercept = np.polyfit(x, y, 1)
        x_hat = np.linspace(x.min(), x.max(), 200)
        y_hat = slope * x_hat + intercept
        plt.plot(x_hat, y_hat)
        plt.title(
            f"{col} per year.\n-1 Means the winner was on average 1 cm shorter than the loser.\nThe line was fitted"
        )

        plt.xlabel("year")
        plt.ylabel("Heigth delta (cm)")
        plt.tight_layout()
        plt.grid(True)
        plt.savefig(f"{OUTPUT_DIR}/{col}.png")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
