from pathlib import Path
import re
import pandas as pd
from scipy import stats


INPUT_DIR = "filtered_heights"


def main():
    data_path = Path(INPUT_DIR)
    if not data_path.exists():
        print(
            "You need to run clean_height_data.py first, this script depends on the data generated by it."
        )
        return 1

    # Should not be needed for filtering, but serves as a small sanity check.
    # It is also conventient to extract the fields from the name.
    p_pattern = re.compile(
        r"filtered_heights/(?P<year>\d{4})/ht_(?P<match_type>[\w_]+).csv"
    )

    dataframes = []
    # Will list every .csv in filtered_heights.
    for p in data_path.rglob("*.csv"):
        match = re.search(p_pattern, str(p))
        # Should always be true unless filtered_heights was manually altered,
        # but this is cleaner.
        if match:
            df = pd.read_csv(p)
            # matches = combine_winners_losers(df)
            dataframes.append(df)

    df = pd.concat(dataframes, ignore_index=True)

    df["dh"] = df["winner_ht"] - df["loser_ht"]

    taller = (df["dh"] > 0).mean()
    shorter = (df["dh"] < 0).mean()
    equal = (df["dh"] == 0).mean()

    print(f"Matches: {len(df)}")
    print(f"Mean height difference:", df["dh"].mean())
    print(f"Median height difference:", df["dh"].median())
    print(f"% winner taller: {taller*100:.2f}")
    print(f"% winner shorter:{shorter*100:.2f}")
    print(f"% equal height: {equal*100:.2f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
